package com.sales.crm.model;

public enum ResourcePermissionEnum {
	
	CUSTOMER_CREATE(1),
	CUSTOMER_READ(2),
	CUSTOMER_UPDATE(3),
	CUSTOMER_DELETE(4),
	CUSTOMER_LIST(5),
	SUPPLIER_CREATE(6),
	SUPPLIER_READ(7),
	SUPPLIER_UPDATE(8),
	SUPPLIER_DELETE(9),
	SUPPLIER_LIST(10),
	AREA_CREATE(11),
	AREA_READ(12),
	AREA_UPDATE(13),
	AREA_DELETE(14),
	AREA_LIST(15),
	BEAT_CREATE(16),
	BEAT_READ(17),
	BEAT_UPDATE(18),
	BEAT_DELETE(19),
	BEAT_LIST(20),
	BEAT_CUSTOMER_ASSIGNMENT(21),
	RESELLER_CREATE(22),
	RESELLER_READ(23),
	RESELLER_UPDATE(24),
	RESELLER_DELETE(25),
	RESELLER_LIST(26),
	RESELLER_APPROVE(27),
	USER_CREATE(28),
	USER_READ(29),
	USER_UPDATE(30),
	USER_DELETE(31),
	USER_LIST(32),
	USER_SCHEDULE_VISIT(33),
	USER_BEAT_ASSIGNMENT(34),
	ROLE_READ(35),
	ROLE_VIEW_RESOURCE_PERMISSION(36),
	ROLE_EDIT_RESOURCE_PERMISSION(37),
	ROLE_LIST(38),
	OTP_LIST(39)
	;
	
	private int resourcePermID;
	
	ResourcePermissionEnum(int resourcePermID){
		this.resourcePermID = resourcePermID;
	}
	
	public int getResourcePermissionID(){
		return resourcePermID;
	}
}
